apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: frontend
spec:
  containers:
    - name: client
      image: khang6294/fullstack-docker-client
      ports:
        - containerPort: 3000